### ISSUE TITLE
Garbled Characters Error on Print Out

### ISSUE THREAD

**Issue by corycpf** [plinth666/epsonsimplecups#12]
We've been trying to isolate a bug and was hoping to get other insights or ideas to troubleshoot. 

**Setup Configuration**
_Printer_: TM-T20ii
_Hardware_: Raspberry Pi 3 running CUPs driver
_Print Management_: Google Cloud Print

Overview: We have a Point of Sale system running a front end on top of WooCommerce WordPress. We use Google Cloud Print to send the print jobs from WooCommerce to the Raspberry Pi 3 running CUPs for print out to the TM-T20ii printer. 

Issue: We are finding on random print outs, the print job is being garbled. We haven't been able to find the pattern causing the bug nor anything in the logs to indicate the issue. The challenge, we can't repro it consistently, but the garbled bug occurs on average between every 50 print jobs. No reset is necessary and normally the next print job works OK.

Here is an image of the garbled characters.
![img_7510](https://user-images.githubusercontent.com/7434668/32739747-ae2ef904-c855-11e7-9503-293fd0b60592.JPG)
![img_7511](https://user-images.githubusercontent.com/7434668/32739749-ae451e78-c855-11e7-9c74-75b7db7e3a02.JPG)

Any insights or ideas on where to troubleshoot would be extremely helpful.

**Comment by Wydna** [comment]
Are the garbled characters always the same?

What should be printed in this place on the printout?

On 13 Nov 2017, at 17:36, Cory Ferreria <notifications@github.com> wrote:

We've been trying to isolate a bug and was hoping to get other insights or ideas to troubleshoot.

Setup Configuration
Printer: TM-T20ii
Hardware: Raspberry Pi 3 running CUPs driver
Print Management: Google Cloud Print

Overview: We have a Point of Sale system running a front end on top of WooCommerce WordPress. We use Google Cloud Print to send the print jobs from WooCommerce to the Raspberry Pi 3 running CUPs for print out to the TM-T20ii printer.

Issue: We are finding on random print outs, the print job is being garbled. We haven't been able to find the pattern causing the bug nor anything in the logs to indicate the issue. The challenge, we can't repro it consistently, but the garbled bug occurs on average between every 50 print jobs. No reset is necessary and normally the next print job works OK.

Here is an image of the garbled characters.



Any insights or ideas on where to troubleshoot would be extremely helpful.

**Comment by corycpf** [comment]
Good questions. 

**Are the garbled characters always the same?** No, similar characters, but the sequence is unique each time. Here is a few more samples. 
![img_7513](https://user-images.githubusercontent.com/7434668/32740701-9769ff4a-c858-11e7-9972-38a22e7499fe.JPG)
![img_7514](https://user-images.githubusercontent.com/7434668/32740702-97864f7e-c858-11e7-90a5-8bdfb8886ca6.JPG)

**What should be printed in this place on the printout?** In some cases, it seems to be just a mis print between the printouts as the next print out occurs. In other cases, it should be the receipt for the customer. Here is a sample of a correct print out.
![img_7515](https://user-images.githubusercontent.com/7434668/32740867-37289032-c859-11e7-9be0-ab9ca488cda8.JPG)

**Comment by Wydna** [comment]
I wonder if the round trip between Wordpress/Woocommerce/Google Cloud Print is the problem?

Any way you can print something similar directly from the Raspberry Pi?

I’m keen to know what’s going on because I want to do something similar!!

/Andy

Sent from my iPhone - 07941 847584

On 13 Nov 2017, at 17:59, Cory Ferreria <notifications@github.com> wrote:

Good questions.

Are the garbled characters always the same? No, similar characters, but the sequence is unique each time. Here is a few more samples.



What should be printed in this place on the printout? In some cases, it seems to be just a mis print between the printouts as the next print out occurs. In other cases, it should be the receipt for the customer. Here is a sample of a correct print out.

**Comment by corycpf** [comment]
Yeah we are exploring that possibility. Our setup works using two Plugins. 
1) Point of Sale Plugin built with REACT
2) Google Cloud Print Plugin managing the print jobs being sent 

We also want to isolate if it's related to the Google Cloud Print management of the printer and the actual driver which I was hopeful to identify if someone has encountered anything similar here. 

For this recommendation "Any way you can print something similar directly from the Raspberry Pi?" Are you thinking bypass Google Cloud Print and print locally to test? Sorry can you clarify.

**Comment by Wydna** [comment]
Yes, Cory.  Print directly from the Raspberry Pi.  If that works, i would then try to print via Google Cloud Print if that’s possible.  Sounds like we’re thinking along the same lines!!

/Andy

Sent from my iPhone - 07941 847584

On 13 Nov 2017, at 18:18, Cory Ferreria <notifications@github.com> wrote:

Yeah we are exploring that possibility. Our setup works using two Plugins.

Point of Sale Plugin built with REACT
Google Cloud Print Plugin managing the print jobs being sent
We also want to isolate if it's related to the Google Cloud Print management of the printer and the actual driver which I was hopeful to identify if someone has encountered anything similar here.

For this recommendation "Any way you can print something similar directly from the Raspberry Pi?" Are you thinking bypass Google Cloud Print and print locally to test? Sorry can you clarify.

**Comment by jan-muller** [comment]
Hi,

We have the same setup (woocommerce/google cloud print / Pi 3 with CUPS / Epson TM-20II) and having the same problem, did you find any solution already? Would like to hear it :)

Jan

**Comment by corycpf** [comment]
Hey Jan.

No.  We are still trying to identify the failure point in the system, since its going across 4 platforms it's been difficult to isolate. The configuration is a powerful setup as a system, but we are seeing it fail at a 20% plus rate.  Way too high.

If we can't resolve the issue, we may need to abandon the configuration, so if you identify any solutions or potential areas to investigate we'd love to hear the details.  Same for anyone else that stumbles upon the issue. If we collaborate, hopefully we can resolve the issue and enable others to adopt it. 

If we discover the issue and or solution, I'll definitely circle back with an update. 

Cory

**Comment by jan-muller** [comment]
Hi Cory,

We also have a fail rate about 20%.

We are now investigating the power source. We have our printer in a restaurant kitchen with a lot of large power consumers. 

This source: (https://www.justanswer.com/printers/6n3s3-epson-tm-t85-prints-fix.html) tells there could be a problem with the power supply, so we will change that just to be sure. 

Our second solution we would like to try is to place a UPS to stabilize the power source. It could be if a large power consumer is powered on (like a oven or stove) there is a small "bump" in de power source. Just to be sure we want to test it.

I will keep you updated.

Jan

**Comment by corycpf** [comment]
Hey Jan,

Thanks for the follow-up. Good news, we are seeing similar failure results.

The power source is an interesting potential root cause. As we had several clients in a similar setup as you describe with large power consumption and heat playing a factor. As a result, we created a "mini" lab isolated as a control to remove any environmental issues. Even in the lab, running a print on a single power source, the fail rate continues. Plus, we have the setup in multiple business locations and the failure persist. As a result, I am doubtful it's a power source issue. 

At this point, we might explore the driver more and or potentially another printer line outside of Epson. See if we can isolate it outside the WooCommerce, Cloud Print and CUPS configuration. If we have another printer such as Star and Failures continue, then we can rule out the Epson printer and driver. 

Collectively I am hopeful we can find a solution, it's a powerful configuration which is extremely scalable, I'd hate to have to abandon it.

**Comment by gajdusek** [comment]
Hi,

I am printing locally on several RPIs with raspbian. (Using forked epsonsimplecups, but I think I haven't done any related code change).

For me this issue disappeared after black-listing kernel module **usblp**. Since then, I didn't observed any problem in last 3 months.

Kernel module usblp (USB Printer Device Class driver) is loaded by default but is not needed by CUPS. Each time a job is to be printed, device file ``/dev/usb/lp0`` (provided by kernel module ``usblp``) is removed to avoid interfering with ongoing print job, and re-enabled after the job is finished. However, this seems to be not enough to prevent interfering. So I just black-listed the ``usblp`` module:

```
# /etc/modprobe.d/local-printer-blacklist.conf

# Blacklist usblp to attempt of fixing printing issues
blacklist usblp
```
I also disabled built-in Rasperry Pi sound card (module **snd-bcm2835**) at the same time to eliminate possible interventions, but probably this is not needed.
 
* Remove volume applet from ``lxde-pi``
* then blacklist sound card kernel module

```
# /etc/modules: kernel modules to load at boot time.
#
# This file contains the names of kernel modules that should be loaded
# at boot time, one per line. Lines beginning with "#" are ignored.
# Parameters can be specified after the module name.

# Disable sound (after removing volume applet from lxde-pi) as it is not needed;
# an attempt to avoid anything which may interfere with printer
#snd-bcm2835
```

**Comment by corycpf** [comment]
Thanks Petr for the information and overview.  I really appreciate you sharing the details here.  I plan on attempting your solution of black-listing kernel module usblp this week.

I'll post a follow-up if it was successful under my setup too. I'm hopeful it will be. This would be huge if so for my project.

**Comment by corycpf** [comment]
@gajdusek Petr, great news! I've done a series of tests this week, looks like your solution solved the problem. I really appreciate the follow-up and insight on a solution, this has cleared the way for us to release an update. 

I'd love to donate a coffee for your time and effort as a Thank You! Drop me your paypal information on my email. 

At this point, I am going to close out this issue. For others on the issue, let us know if it solves it for you too. If I encounter the issue in the coming weeks, I'll reopen the issue.

**Comment by shudis** [comment]
@Gajdusek - It also corrected our problem with a Custom America receipt printer that we were struggling with for 2 days.  Thanks!!

**Comment by MarcSallent** [comment]
Hi! I was having this issue too and it helped me solve it. Thanks!

@plinth666 : As I see that many people is having the same issue, I suggest giving this issue more visibility or adding it to the README file
