### ISSUE TITLE
Dynamic length

### ISSUE THREAD

**Issue by manjifico** [plinth666/epsonsimplecups#18]
Great project and it works really well.

Is it possible to make the printer cut dynamic lengths depending on the text length?

**Comment by plinth666** [comment]
That's a great question, and I wish I knew the answer.The challenge lies in how modern printers work. Typically a driver requests a particular paper size and the printer responds or the driver asks the printer for a set of sizes and the printer responds.It makes printing to continuous feed printers a challenge.In my case, I just wanted this so my daughter could make and print a shopping list from her iPad. That's it. Seriously.If you really want to use this kind of printer for printing receipts, you might consider building an abstraction layer for doing that that doesn't require cups.Here's why: you can pre-download an image to this printer for printing a company logo at the top, say. Printing a continuous list in the plain font is not only faster, it's way more legible.This printer speaks the Epson ESC/POS protocol so to talk to it, you need to open a connection to the appropriate USB port and spew raw text to it.The unfortunate thing is that you are now writing your own custom print driver and will have to redo that if you need to use a different model of printer.Best of luck!On Jan 24, 2020 8:53 AM, manjifico <notifications@github.com> wrote:Great project and it works really well.
Is it possible to make the printer cut dynamic lengths depending on the text length?

**Comment by plinth666** [comment]
I should also add that many of the ESC codes in this printer are unchanged from the Epson mx-80 dot matrix printer that I drove from an Apple II in 1980.On Jan 24, 2020 8:53 AM, manjifico <notifications@github.com> wrote:Great project and it works really well.
Is it possible to make the printer cut dynamic lengths depending on the text length?

**Comment by manjifico** [comment]
Thank you for your response and for your work.
