### ISSUE TITLE
height block

### ISSUE THREAD

**Issue by natxopedreira** [plinth666/epsonsimplecups#2]
Hi

First, thanks for the driver, works great!!! and its the only way to print in my TM20II from my raspberry.

Im using it to print large images, and i found an estrange behavior, because i get small blank lines in my print (aprox. 1px height), maybe you can give me a clue?

regards
natxo pedreira gonzalez

**Comment by plinth666** [comment]
I've seen that. It happens between bands of the image data and appears 
to be an issue in the printer itself.
The way to fix that is to either buffer the entire image (which leads to 
a long delay between print job sent and paper out) or to use a different 
mechanism to get the image on the page (none of the other ways seemed 
reliable), or to scan the image and look for blank lines and use a 
variable buffering mechanism to hide the holes.

**Comment by natxopedreira** [comment]
thanks!! I understand, also explains why im not getting the lines printing at smaller size and resolution.
