### ISSUE TITLE
Thankyou! Would you mind a step-by-step

### ISSUE THREAD

**Issue by hawkinsjon** [plinth666/epsonsimplecups#3]
Thank you very much for creating this driver!

I have an Epson T20II connected via USB to a RPI2 and I would like to use cups. Sounds like this is a perfect match.

By any chance, would you be willing to give me a step by step on how to install your driver on my pi? I must be doing something wrong.

Thanks!
Jon

![img_1703](https://cloud.githubusercontent.com/assets/3512179/8635869/4505f3f6-280c-11e5-8a83-966f486dc3bc.JPG)

**Comment by plinth666** [comment]
What I did was start with a stock pi, with raspberrian, brought it up to 
date, installed cups, set it up.
I built and tested the driver on my laptop, then copied the source over 
to the pi.
In the directory with the makefile (IIRC):
make ; sudo make install

Go to the CUPS page, install the printer (there is a very long wait 
while it loads EVERY stinking Epson driver) and select the mine.
Configure and print a test page.

See also:
https://github.com/plinth666/epsonsimplecups/blob/master/README.md

I'm running the on a PiB, I have not tried a Pi2, but it is so simple, I 
can't imagine it having issues.

**Comment by hawkinsjon** [comment]
What’s the easiest way for me to copy your source code over to the pi. Can i do a curl some how and then run the sudo make install command? Sorry i’m a little clueless :)

## 

Jon

**Comment by plinth666** [comment]
Open the web browser, use the download link to here:
https://github.com/plinth666/epsonsimplecups/archive/master.zip
(or curl)
gunzip it

etc.

**Comment by hawkinsjon** [comment]
I can't thank you enough! Woo hoo!

![img_1741](https://cloud.githubusercontent.com/assets/3512179/8635932/7bda079c-2810-11e5-9b49-bbdb344056ac.JPG)

**Comment by wraybowling** [comment]
I am getting a raspberry pi soon and I would like to thank you in advance. Looking forward to trying this out especially since I'll never get my hands on a LittlePrinter now.

**Comment by kenkaiten** [comment]
I want to say thank you to you too.
I use your code and installed on Ubuntu Mate 15.04 on Raspberry PI 2 and It works.

Thanks again.

**Comment by csware** [comment]
https://www.youtube.com/watch?v=fGOcgz6z81I
